SELECT TOP 1000 [DifferentialID]
,[DiffName]
,[PercentFull]
,[Available]
,[Occupied]
,[Total]
,[ResetTime]
,[ResetVal]
,[Yellow]
,[Red]
,[ThresholdStatus]
,[Type]
,[Math]
,[SiteID]
,[SortOrder]
,[IsAccessDiff]
,[SignThreshHigh]
,[CreatedDate]
,[CreatedUser]
,[ModifiedDate]
,[ModifiedUser]
FROM [McGann].[dbo].[CM.Differential]